// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        (unknown)
// source: merkeltrie.proto

package protocol

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CHILDTYPE int32

const (
	CHILDTYPE_NONE  CHILDTYPE = 0
	CHILDTYPE_INNER CHILDTYPE = 1
	CHILDTYPE_LEAF  CHILDTYPE = 2
)

// Enum value maps for CHILDTYPE.
var (
	CHILDTYPE_name = map[int32]string{
		0: "NONE",
		1: "INNER",
		2: "LEAF",
	}
	CHILDTYPE_value = map[string]int32{
		"NONE":  0,
		"INNER": 1,
		"LEAF":  2,
	}
)

func (x CHILDTYPE) Enum() *CHILDTYPE {
	p := new(CHILDTYPE)
	*p = x
	return p
}

func (x CHILDTYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CHILDTYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_merkeltrie_proto_enumTypes[0].Descriptor()
}

func (CHILDTYPE) Type() protoreflect.EnumType {
	return &file_merkeltrie_proto_enumTypes[0]
}

func (x CHILDTYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CHILDTYPE.Descriptor instead.
func (CHILDTYPE) EnumDescriptor() ([]byte, []int) {
	return file_merkeltrie_proto_rawDescGZIP(), []int{0}
}

type Child struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sublocation []byte    `protobuf:"bytes,1,opt,name=sublocation,proto3" json:"sublocation,omitempty"`
	Hash        []byte    `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Childtype   CHILDTYPE `protobuf:"varint,3,opt,name=childtype,proto3,enum=protocol.CHILDTYPE" json:"childtype,omitempty"` //int64 count = 4;
}

func (x *Child) Reset() {
	*x = Child{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merkeltrie_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Child) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Child) ProtoMessage() {}

func (x *Child) ProtoReflect() protoreflect.Message {
	mi := &file_merkeltrie_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Child.ProtoReflect.Descriptor instead.
func (*Child) Descriptor() ([]byte, []int) {
	return file_merkeltrie_proto_rawDescGZIP(), []int{0}
}

func (x *Child) GetSublocation() []byte {
	if x != nil {
		return x.Sublocation
	}
	return nil
}

func (x *Child) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Child) GetChildtype() CHILDTYPE {
	if x != nil {
		return x.Childtype
	}
	return CHILDTYPE_NONE
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Children []*Child `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merkeltrie_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_merkeltrie_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_merkeltrie_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetChildren() []*Child {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_merkeltrie_proto protoreflect.FileDescriptor

var file_merkeltrie_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x65, 0x72, 0x6b, 0x65, 0x6c, 0x74, 0x72, 0x69, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x70, 0x0a, 0x05,
	0x43, 0x68, 0x69, 0x6c, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x73, 0x75, 0x62, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x31, 0x0a, 0x09, 0x63,
	0x68, 0x69, 0x6c, 0x64, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x48, 0x49, 0x4c, 0x44, 0x54,
	0x59, 0x50, 0x45, 0x52, 0x09, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x74, 0x79, 0x70, 0x65, 0x22, 0x33,
	0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64,
	0x72, 0x65, 0x6e, 0x2a, 0x2a, 0x0a, 0x09, 0x43, 0x48, 0x49, 0x4c, 0x44, 0x54, 0x59, 0x50, 0x45,
	0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4e,
	0x4e, 0x45, 0x52, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x45, 0x41, 0x46, 0x10, 0x02, 0x42,
	0x25, 0x0a, 0x23, 0x69, 0x6f, 0x2e, 0x62, 0x75, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x73, 0x64,
	0x6b, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_merkeltrie_proto_rawDescOnce sync.Once
	file_merkeltrie_proto_rawDescData = file_merkeltrie_proto_rawDesc
)

func file_merkeltrie_proto_rawDescGZIP() []byte {
	file_merkeltrie_proto_rawDescOnce.Do(func() {
		file_merkeltrie_proto_rawDescData = protoimpl.X.CompressGZIP(file_merkeltrie_proto_rawDescData)
	})
	return file_merkeltrie_proto_rawDescData
}

var file_merkeltrie_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_merkeltrie_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_merkeltrie_proto_goTypes = []interface{}{
	(CHILDTYPE)(0), // 0: protocol.CHILDTYPE
	(*Child)(nil),  // 1: protocol.Child
	(*Node)(nil),   // 2: protocol.Node
}
var file_merkeltrie_proto_depIdxs = []int32{
	0, // 0: protocol.Child.childtype:type_name -> protocol.CHILDTYPE
	1, // 1: protocol.Node.children:type_name -> protocol.Child
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_merkeltrie_proto_init() }
func file_merkeltrie_proto_init() {
	if File_merkeltrie_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_merkeltrie_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Child); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merkeltrie_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_merkeltrie_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_merkeltrie_proto_goTypes,
		DependencyIndexes: file_merkeltrie_proto_depIdxs,
		EnumInfos:         file_merkeltrie_proto_enumTypes,
		MessageInfos:      file_merkeltrie_proto_msgTypes,
	}.Build()
	File_merkeltrie_proto = out.File
	file_merkeltrie_proto_rawDesc = nil
	file_merkeltrie_proto_goTypes = nil
	file_merkeltrie_proto_depIdxs = nil
}
